import {
  FaBell,
  FaBolt,
  FaCalendarCheck,
  FaChevronLeft,
  FaChevronRight,
  FaClock,
  FaCoins,
  FaEye,
  FaFilter,
  FaFlag,
  FaGamepad,
  FaGem,
  FaGift,
  FaGauge,
  FaGear,
  FaGlobe,
  FaCrown,
  FaHouse,
  FaLock,
  FaMedal,
  FaPhone,
  FaPlay,
  FaRotate,
  FaShieldHalved,
  FaBagShopping,
  FaStar,
  FaTrophy,
  FaUser,
  FaUsers,
  FaWallet,
  FaWifi,
  FaXmark,
} from 'react-icons/fa6'

const icons = {
  bell: FaBell,
  bolt: FaBolt,
  calendar: FaCalendarCheck,
  chevronLeft: FaChevronLeft,
  chevronRight: FaChevronRight,
  clock: FaClock,
  coin: FaCoins,
  eye: FaEye,
  filter: FaFilter,
  flag: FaFlag,
  gamepad: FaGamepad,
  gem: FaGem,
  gift: FaGift,
  gauge: FaGauge,
  gear: FaGear,
  globe: FaGlobe,
  jackpot: FaCrown,
  home: FaHouse,
  lock: FaLock,
  medal: FaMedal,
  phone: FaPhone,
  play: FaPlay,
  refresh: FaRotate,
  shield: FaShieldHalved,
  store: FaBagShopping,
  star: FaStar,
  trophy: FaTrophy,
  user: FaUser,
  users: FaUsers,
  wallet: FaWallet,
  wifiOff: FaWifi,
  close: FaXmark,
}

export function Icon({ name, icon, ...props }) {
  const Component = icons[name || icon] || FaStar
  return <Component aria-hidden="true" {...props} />
}

export default Icon
