import httpClient, {
  API_BASE_URL,
  API_ENDPOINTS,
  ApiError,
  RUNTIME_CONFIG,
  doCheckin,
  fetchActivities,
  fetchArenaLeaderboard,
  fetchArenaList,
  fetchGameDetail,
  fetchGames,
  fetchLeaderboard,
  fetchLobbyData,
  fetchProducts,
  fetchTasks,
  fetchUserBalance,
  fetchUserProfile,
  get,
  initReq,
  joinArena,
  post,
  purchaseProduct,
  redeemCode,
  setWebSocketConnector,
  shouldPreferRemote,
  shouldUseLocalOnly,
  spinWheel,
  claimTaskReward,
} from './httpClient';
import socketClient, { WS_EVENTS, useWebSocket, wsClient } from './socketClient';
import { playerStore } from './player.js';

// The real lobby login endpoint returns a ws/wss URL as plain text.
// Registering the connector here avoids a dynamic import cycle in httpClient.
setWebSocketConnector((url) => socketClient.connect(url));

export {
  API_BASE_URL,
  API_ENDPOINTS,
  ApiError,
  RUNTIME_CONFIG,
  WS_EVENTS,
  claimTaskReward,
  doCheckin,
  fetchActivities,
  fetchArenaLeaderboard,
  fetchArenaList,
  fetchGameDetail,
  fetchGames,
  fetchLeaderboard,
  fetchLobbyData,
  fetchProducts,
  fetchTasks,
  fetchUserBalance,
  fetchUserProfile,
  get,
  httpClient,
  initReq,
  joinArena,
  playerStore,
  post,
  purchaseProduct,
  redeemCode,
  setWebSocketConnector,
  shouldPreferRemote,
  shouldUseLocalOnly,
  socketClient,
  spinWheel,
  useWebSocket,
  wsClient,
};
